[build]
  command = "echo '빌드 과정을 실행하여 Blobs 환경변수 주입'"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# 클라이언트 앱에서 /api/... 로 요청하는 모든 주소를 client-api 함수로 연결합니다.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/client-api"
  status = 200